version: '3.7'

services:
  broadwaySelenium:
    container_name: broadwaySelenium 
    restart: always
    image: seleniarm/standalone-chromium
    volumes:
      - /dev/shm:/dev/shm
      - "./offlinePages:/mnt/offlinePages"
    ports:
      - 5901:5900
      - 4444:4444
      - 7900:7900
  broadwayRunner:
    container_name: broadwayRunner
    restart: no
    build: 
      context: .
      dockerfile: Dockerfile
    image: broadwayrunner
    volumes:
      - ".:/home"
    depends_on:
      - broadwaySelenium
    # entrypoint: ["pytest"]
    # entrypoint : ['python', 'runDefault.py']

 